### ISSUE TITLE
Type referencing a function instead of the type

### ISSUE THREAD

**Issue by Darova93** [pragdave/e4p2-hangman#2]
Shouldn't this line be changed from this

https://github.com/pragdave/e4p2-hangman/blob/64e8bd7c6658db2a7c36c45ef72431d9c2989d39/text_client/lib/impl/player.ex#L4

to this:

```elixir
@typep tally :: Hangman.Type.tally() 
```

Otherwise it seems to reference the Hangman.tally function

**Comment by pragdave** [comment]
You are absolutely right. I've pushed changes to the affected branches.

Good spotting.

Dave
